[package]
name = "libstorage"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "sqlite"] }
redis = { version = "0.24", features = ["tokio-comp"] }
tokio = { version = "1.0", features = ["full"] }
once_cell = "1.8"
dotenvy = "0.15"
