[package]
name = "demo-passkey"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
askama = "0.12.1"
axum = { workspace = true }
axum-core = { workspace = true }
tokio = { workspace = true }

oauth2_passkey.workspace = true
libaxum.workspace = true

dotenv = { workspace = true }
http = { workspace = true }
