[package]
name = "libsession"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
redis = { version = "0.28.2", features = ["tokio-comp"] }
axum = "0.8.1"
axum-extra = { version = "0.10.0", features = ["typed-header"] }
chrono = { version = "0.4.39", features = ["serde"] }
http = "1.2.0"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { workspace = true }
dotenv = "0.15.0"
ring = "0.17.8"
async-trait = "0.1.86"
headers = "0.4.0"
base64 = "0.22.1"
tracing = "0.1.41"
libuserdb = { path = "../libuserdb" }
cookie = "0.18"
