[package]
name = "liboauth2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
redis = { version = "0.28.2", features = ["tokio-comp"] }
axum = "0.8.1"
axum-extra = { version = "0.10.0", features = ["typed-header"] }
chrono = { version = "0.4.39", features = ["serde"] }
dashmap = "6.1.0"
http = "1.2.0"
jsonwebtoken = "9.3.1"
moka = { version = "0.12.10", features = ["future"] }
once_cell = "1.20.3"
pkcs1 = "0.7.5"
reqwest = { version = "0.12.12", features = ["json"] }
rsa = "0.9.7"
serde = "1.0.217"
serde_json = "1.0.138"
thiserror = "2.0.11"
tokio = { workspace = true }
url = "2.5.4"
dotenv = "0.15.0"
ring = "0.17.8"
async-trait = "0.1.86"
headers = "0.4.0"
sha2 = "0.10.8"
base64 = "0.22.1"
askama = { version = "0.12.1", features = ["serde-json"] }
tracing = "0.1.41"
libsession = { workspace = true }
libuserdb = { workspace = true }

[build-dependencies]
askama = "0.12"

[package.metadata.askama]
dir = "templates"
