[package]
name = "libpasskey"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = { workspace = true }
base64 = "0.22.1"
ciborium = "0.2.2"
dotenv = "0.15.0"
oid-registry = "0.8.0"
ring = { version = "0.17.8", features = ["std"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.11"
tokio = { workspace = true }
uuid = { version = "1.11.0", features = ["atomic", "md5", "sha1", "v4"] }
webpki = { version = "0.22.4", features = ["std"] }
x509-parser = { version = "0.16.0", features = ["validate", "verify"] }
