[package]
name = "libpasskey"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
askama = { version = "0.12.1", features = ["serde-json"] }
async-trait = "0.1"
axum.workspace = true
axum-core = "0.5.0"
base64 = "0.22.1"
ciborium = "0.2.2"
dotenv = "0.15.0"
oid-registry = "0.8.1"
redis = { version = "0.28.2", features = ["tokio-comp"] }
ring = { version = "0.17.8", features = ["std"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
sqlx = { version = "0.8", features = [
    "any",
    "chrono", 
    "json", 
    "macros",
    "mysql", 
    "postgres", 
    "regexp", 
    "runtime-tokio-native-tls", 
    "runtime-tokio-rustls", 
    "sqlite",
    "runtime-async-std-native-tls"
], default-features = false }
thiserror = "2.0.11"
tokio = { workspace = true }
uuid = { version = "1.13.1", features = ["atomic", "md5", "sha1", "v4"] }
webpki = { version = "0.22.4", features = ["std"] }
x509-parser = { version = "0.17.0", features = ["validate", "verify"] }
