[workspace]
members = [
    "demo-integration",
    "demo-oauth2",
    "demo-passkey",
    "liboauth2",
    "libsession",
    "libpasskey",
    "libuserdb",
    "libaxum",
    "libstorage",
    "libauth",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
liboauth2 = { path = "./liboauth2" }
libpasskey = { path = "./libpasskey" }
libsession = { path = "./libsession" }
libuserdb = { path = "./libuserdb" }
libaxum = { path = "./libaxum" }
libstorage = { path = "./libstorage" }
libauth = { path = "./libauth" }

async-trait = "0.1.87"
axum = { version = "0.8", features = ["http2", "macros", "multipart"] }
dotenv = "0.15.0"

http = "1.2.0"
ring = "0.17.11"
headers = "0.4.0"
base64 = "0.22.1"

tokio = { version = "1.43", features = ["bytes", "fs", "io-std", "macros", "parking_lot", "rt-multi-thread", "signal-hook-registry", "socket2", "sync", "time", "tracing"] }
rustls = { version = "0.23.23", features = ["ring"] }
axum-core = "0.5.0"
axum-extra = { version = "0.10.0", features = ["typed-header"] }
chrono = { version = "0.4.40", features = ["serde"] }
tracing = "0.1.41"
thiserror = "2.0.12"
serde_json = "1.0.140"
serde = { version = "1.0.218", features = ["derive"] }
uuid = { version = "1.15", features = ["v4"] }
urlencoding = "2.1.3"

sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "postgres", "chrono", "json", "uuid"] }

# sqlx = { version = "0.8", features = [
#     "any",
#     "chrono", 
#     "json", 
#     "macros",
#     "mysql", 
#     "postgres", 
#     "regexp", 
#     "runtime-tokio-native-tls", 
#     "runtime-tokio-rustls", 
#     "sqlite",
#     "runtime-async-std-native-tls"
# ], default-features = false }
