[package]
name = "libsession"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0.96"
redis = { version = "0.29.0", features = ["tokio-comp"] }
chrono = { version = "0.4.39", features = ["serde"] }
http = "1.2.0"
serde = "1.0.218"
serde_json = "1.0.139"
tokio = { workspace = true }
dotenv = "0.15.0"
ring = "0.17.11"
async-trait = "0.1.86"
headers = "0.4.0"
base64 = "0.22.1"
tracing = "0.1.41"
libuserdb = { workspace = true }
